### ISSUE TITLE
I'll edit

### ISSUE THREAD

**Issue by MCloverz** [smileycreations15/ScratchBux#2]
@smileycreations15 I'll start.

**Comment by smileycreations15** [comment]
@MCloverz I will add my own template.

**Comment by MCloverz** [comment]
> @MCloverz I will add my own template.

How do you add an icon to the website? I see you have done it.

**Comment by smileycreations15** [comment]
> > @MCloverz I will add my own template.
> 
> How do you add an icon to the website? I see you have done it.

Give me the icon and I will add it. I use meta tags for this.

**Comment by smileycreations15** [comment]
@MCloverz Can you add more stoof?

**Comment by MCloverz** [comment]
> @MCloverz Can you add more stoof?

In a sec.

> > > @MCloverz I will add my own template.
> > 
> > 
> > How do you add an icon to the website? I see you have done it.
> 
> Give me the icon and I will add it. I use meta tags for this.

Can you give me a link to a tutorial or something?

**Comment by smileycreations15** [comment]
> > @MCloverz Can you add more stoof?
> 
> In a sec.
> 
> > > > @MCloverz I will add my own template.
> > > 
> > > 
> > > How do you add an icon to the website? I see you have done it.
> > 
> > 
> > Give me the icon and I will add it. I use meta tags for this.
> 
> Can you give me a link to a tutorial or something?

Add `<meta rel="icon" content="/path/to/icon">` to the head section.

**Comment by smileycreations15** [comment]
cc @MCloverz

**Comment by MCloverz** [comment]
> > > @MCloverz Can you add more stoof?
> > 
> > 
> > In a sec.
> > > > > @MCloverz I will add my own template.
> > > > 
> > > > 
> > > > How do you add an icon to the website? I see you have done it.
> > > 
> > > 
> > > Give me the icon and I will add it. I use meta tags for this.
> > 
> > 
> > Can you give me a link to a tutorial or something?
> 
> Add `<meta rel="icon" content="/path/to/icon">` to the head section.

I mean a website with a theme.

**Comment by smileycreations15** [comment]
> > > > @MCloverz Can you add more stoof?
> > > 
> > > 
> > > In a sec.
> > > > > > @MCloverz I will add my own template.
> > > > > 
> > > > > 
> > > > > How do you add an icon to the website? I see you have done it.
> > > > 
> > > > 
> > > > Give me the icon and I will add it. I use meta tags for this.
> > > 
> > > 
> > > Can you give me a link to a tutorial or something?
> > 
> > 
> > Add `<meta rel="icon" content="/path/to/icon">` to the head section.
> 
> I mean a website with a theme.

@MCloverz Upload a favicon.png to the repository and it will work. I will take care of the rest.

**Comment by smileycreations15** [comment]
cc @MCloverz

**Comment by MCloverz** [comment]
> > > > > @MCloverz Can you add more stoof?
> > > > 
> > > > 
> > > > In a sec.
> > > > > > > @MCloverz I will add my own template.
> > > > > > 
> > > > > > 
> > > > > > How do you add an icon to the website? I see you have done it.
> > > > > 
> > > > > 
> > > > > Give me the icon and I will add it. I use meta tags for this.
> > > > 
> > > > 
> > > > Can you give me a link to a tutorial or something?
> > > 
> > > 
> > > Add `<meta rel="icon" content="/path/to/icon">` to the head section.
> > 
> > 
> > I mean a website with a theme.
> 
> @MCloverz Upload a favicon.png to the repository and it will work. I will take care of the rest.

Thanks!

**Comment by MCloverz** [comment]
> > > > > > @MCloverz Can you add more stoof?
> > > > > 
> > > > > 
> > > > > In a sec.
> > > > > > > > @MCloverz I will add my own template.
> > > > > > > 
> > > > > > > 
> > > > > > > How do you add an icon to the website? I see you have done it.
> > > > > > 
> > > > > > 
> > > > > > Give me the icon and I will add it. I use meta tags for this.
> > > > > 
> > > > > 
> > > > > Can you give me a link to a tutorial or something?
> > > > 
> > > > 
> > > > Add `<meta rel="icon" content="/path/to/icon">` to the head section.
> > > 
> > > 
> > > I mean a website with a theme.
> > 
> > 
> > @MCloverz Upload a favicon.png to the repository and it will work. I will take care of the rest.
> 
> Thanks!

@smileycreations15 No, I mean that _I_ want to learn how to do it myself.

**Comment by FrenchBread49** [comment]
What

**Comment by smileycreations15** [comment]
> > > > > > > @MCloverz Can you add more stoof?
> > > > > > 
> > > > > > 
> > > > > > In a sec.
> > > > > > > > > @MCloverz I will add my own template.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > How do you add an icon to the website? I see you have done it.
> > > > > > > 
> > > > > > > 
> > > > > > > Give me the icon and I will add it. I use meta tags for this.
> > > > > > 
> > > > > > 
> > > > > > Can you give me a link to a tutorial or something?
> > > > > 
> > > > > 
> > > > > Add `<meta rel="icon" content="/path/to/icon">` to the head section.
> > > > 
> > > > 
> > > > I mean a website with a theme.
> > > 
> > > 
> > > @MCloverz Upload a favicon.png to the repository and it will work. I will take care of the rest.
> > 
> > 
> > Thanks!
> 
> @smileycreations15 No, I mean that _I_ want to learn how to do it myself.

It is complicated with a theme.

**Comment by MCloverz** [comment]
> > > > > > > > @MCloverz Can you add more stoof?
> > > > > > > 
> > > > > > > 
> > > > > > > In a sec.
> > > > > > > > > > @MCloverz I will add my own template.
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > How do you add an icon to the website? I see you have done it.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Give me the icon and I will add it. I use meta tags for this.
> > > > > > > 
> > > > > > > 
> > > > > > > Can you give me a link to a tutorial or something?
> > > > > > 
> > > > > > 
> > > > > > Add `<meta rel="icon" content="/path/to/icon">` to the head section.
> > > > > 
> > > > > 
> > > > > I mean a website with a theme.
> > > > 
> > > > 
> > > > @MCloverz Upload a favicon.png to the repository and it will work. I will take care of the rest.
> > > 
> > > 
> > > Thanks!
> > 
> > 
> > @smileycreations15 No, I mean that _I_ want to learn how to do it myself.
> 
> It is complicated with a theme.

Can you give me a link to a tutorial or something or just explain it here?

**Comment by smileycreations15** [comment]
> > > > > > > > > @MCloverz Can you add more stoof?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > In a sec.
> > > > > > > > > > > @MCloverz I will add my own template.
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > How do you add an icon to the website? I see you have done it.
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Give me the icon and I will add it. I use meta tags for this.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Can you give me a link to a tutorial or something?
> > > > > > > 
> > > > > > > 
> > > > > > > Add `<meta rel="icon" content="/path/to/icon">` to the head section.
> > > > > > 
> > > > > > 
> > > > > > I mean a website with a theme.
> > > > > 
> > > > > 
> > > > > @MCloverz Upload a favicon.png to the repository and it will work. I will take care of the rest.
> > > > 
> > > > 
> > > > Thanks!
> > > 
> > > 
> > > @smileycreations15 No, I mean that _I_ want to learn how to do it myself.
> > 
> > 
> > It is complicated with a theme.
> 
> Can you give me a link to a tutorial or something or just explain it here?

You need to edit _includes/head.html and add the `<link rel="shortcut icon" type="image/png" href="/{REPO NAME HERE}/favicon.png">` line. Then create a favicon.png file in the repo.

**Comment by smileycreations15** [comment]
cc @MCloverz

**Comment by MCloverz** [comment]
-snip-
> > > > > > > > Add `<meta rel="icon" content="/path/to/icon">` to the head section.
> > > > > > > 
> > > > > > > 
> > > > > > > I mean a website with a theme.
> > > > > > 
> > > > > > 
> > > > > > @MCloverz Upload a favicon.png to the repository and it will work. I will take care of the rest.
> > > > > 
> > > > > 
> > > > > Thanks!
> > > > 
> > > > 
> > > > @smileycreations15 No, I mean that _I_ want to learn how to do it myself.
> > > 
> > > 
> > > It is complicated with a theme.
> > 
> > 
> > Can you give me a link to a tutorial or something or just explain it here?
> 
> https://medium.com/@xiang_zhou/how-to-add-a-favicon-to-your-jekyll-site-2ac2179cc2ed

Is there a way that doesn't involve terminal or git?

**Comment by smileycreations15** [comment]
> -snip-
> 
> > > > > > > > > Add `<meta rel="icon" content="/path/to/icon">` to the head section.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > I mean a website with a theme.
> > > > > > > 
> > > > > > > 
> > > > > > > @MCloverz Upload a favicon.png to the repository and it will work. I will take care of the rest.
> > > > > > 
> > > > > > 
> > > > > > Thanks!
> > > > > 
> > > > > 
> > > > > @smileycreations15 No, I mean that _I_ want to learn how to do it myself.
> > > > 
> > > > 
> > > > It is complicated with a theme.
> > > 
> > > 
> > > Can you give me a link to a tutorial or something or just explain it here?
> > 
> > 
> > https://medium.com/@xiang_zhou/how-to-add-a-favicon-to-your-jekyll-site-2ac2179cc2ed
> 
> Is there a way that doesn't involve terminal or git?

Yes, edit _includes/head.html [(here)](https://github.com/smileycreations15/ScratchBux/new/master?filename=_includes/head.html) and paste in `<link rel="icon" content="/{NAME OF REPO}/{NAME OF FAVICON FILE}">`. Then save the file. cc @mcl

**Comment by MCloverz** [comment]
> > -snip-
> > > > > > > > > > Add `<meta rel="icon" content="/path/to/icon">` to the head section.
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > I mean a website with a theme.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > @MCloverz Upload a favicon.png to the repository and it will work. I will take care of the rest.
> > > > > > > 
> > > > > > > 
> > > > > > > Thanks!
> > > > > > 
> > > > > > 
> > > > > > @smileycreations15 No, I mean that _I_ want to learn how to do it myself.
> > > > > 
> > > > > 
> > > > > It is complicated with a theme.
> > > > 
> > > > 
> > > > Can you give me a link to a tutorial or something or just explain it here?
> > > 
> > > 
> > > https://medium.com/@xiang_zhou/how-to-add-a-favicon-to-your-jekyll-site-2ac2179cc2ed
> > 
> > 
> > Is there a way that doesn't involve terminal or git?
> 
> Yes, edit _includes/head.html [(here)](https://github.com/smileycreations15/ScratchBux/new/master?filename=_includes/head.html) and paste in `<meta name="icon" content="/{NAME OF REPO}/{NAME OF FAVICON FILE}">`. Then save the file. cc @MCloverz

Thanks.

**Comment by smileycreations15** [comment]
> > > -snip-
> > > > > > > > > > > Add `<meta rel="icon" content="/path/to/icon">` to the head section.
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > I mean a website with a theme.
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > @MCloverz Upload a favicon.png to the repository and it will work. I will take care of the rest.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Thanks!
> > > > > > > 
> > > > > > > 
> > > > > > > @smileycreations15 No, I mean that _I_ want to learn how to do it myself.
> > > > > > 
> > > > > > 
> > > > > > It is complicated with a theme.
> > > > > 
> > > > > 
> > > > > Can you give me a link to a tutorial or something or just explain it here?
> > > > 
> > > > 
> > > > https://medium.com/@xiang_zhou/how-to-add-a-favicon-to-your-jekyll-site-2ac2179cc2ed
> > > 
> > > 
> > > Is there a way that doesn't involve terminal or git?
> > 
> > 
> > Yes, edit _includes/head.html [(here)](https://github.com/smileycreations15/ScratchBux/new/master?filename=_includes/head.html) and paste in `<meta name="icon" content="/{NAME OF REPO}/{NAME OF FAVICON FILE}">`. Then save the file. cc @MCloverz
> 
> Thanks.

Now please work on the site.

**Comment by MCloverz** [comment]
> > > > -snip-
> > > > > > > > > > > > Add `<meta rel="icon" content="/path/to/icon">` to the head section.
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > I mean a website with a theme.
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > @MCloverz Upload a favicon.png to the repository and it will work. I will take care of the rest.
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Thanks!
> > > > > > > > 
> > > > > > > > 
> > > > > > > > @smileycreations15 No, I mean that _I_ want to learn how to do it myself.
> > > > > > > 
> > > > > > > 
> > > > > > > It is complicated with a theme.
> > > > > > 
> > > > > > 
> > > > > > Can you give me a link to a tutorial or something or just explain it here?
> > > > > 
> > > > > 
> > > > > https://medium.com/@xiang_zhou/how-to-add-a-favicon-to-your-jekyll-site-2ac2179cc2ed
> > > > 
> > > > 
> > > > Is there a way that doesn't involve terminal or git?
> > > 
> > > 
> > > Yes, edit _includes/head.html [(here)](https://github.com/smileycreations15/ScratchBux/new/master?filename=_includes/head.html) and paste in `<meta name="icon" content="/{NAME OF REPO}/{NAME OF FAVICON FILE}">`. Then save the file. cc @MCloverz
> > 
> > 
> > Thanks.
> 
> Now please work on the site.

Oh, yes, sorry!

**Comment by smileycreations15** [comment]
> > > > > -snip-
> > > > > > > > > > > > > Add `<meta rel="icon" content="/path/to/icon">` to the head section.
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > I mean a website with a theme.
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > @MCloverz Upload a favicon.png to the repository and it will work. I will take care of the rest.
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > Thanks!
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > @smileycreations15 No, I mean that _I_ want to learn how to do it myself.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > It is complicated with a theme.
> > > > > > > 
> > > > > > > 
> > > > > > > Can you give me a link to a tutorial or something or just explain it here?
> > > > > > 
> > > > > > 
> > > > > > https://medium.com/@xiang_zhou/how-to-add-a-favicon-to-your-jekyll-site-2ac2179cc2ed
> > > > > 
> > > > > 
> > > > > Is there a way that doesn't involve terminal or git?
> > > > 
> > > > 
> > > > Yes, edit _includes/head.html [(here)](https://github.com/smileycreations15/ScratchBux/new/master?filename=_includes/head.html) and paste in `<meta name="icon" content="/{NAME OF REPO}/{NAME OF FAVICON FILE}">`. Then save the file. cc @MCloverz
> > > 
> > > 
> > > Thanks.
> > 
> > 
> > Now please work on the site.
> 
> Oh, yes, sorry!

Keep this tab always open. You should see a `(1)` in the title when you have a new reply.

**Comment by smileycreations15** [comment]
cc @MCloverz

**Comment by MCloverz** [comment]
> cc @MCloverz

Okay.

**Comment by smileycreations15** [comment]
> > cc @MCloverz
> 
> Okay.

Can you create a favicon then upload it as favicon.png? cc @MCloverz

**Comment by MCloverz** [comment]
> > > cc @MCloverz
> > 
> > 
> > Okay.
> 
> Can you create a favicon then upload it as favicon.png? cc @MCloverz

Okay. I am trying the favicon thing on one of my repos, but it's not working. I'll add a favicon to ScratchBux.
https://github.com/MCloverz/sandbox/

**Comment by MCloverz** [comment]
> > > > cc @MCloverz
> > > 
> > > 
> > > Okay.
> > 
> > 
> > Can you create a favicon then upload it as favicon.png? cc @MCloverz
> 
> Okay. I am trying the favicon thing on one of my repos, but it's not working. I'll add a favicon to ScratchBux.
> https://github.com/MCloverz/sandbox/

Just uploaded the logo
cc @smileycreations15

**Comment by smileycreations15** [comment]
> > > > cc @MCloverz
> > > 
> > > 
> > > Okay.
> > 
> > 
> > Can you create a favicon then upload it as favicon.png? cc @MCloverz
> 
> Okay. I am trying the favicon thing on one of my repos, but it's not working. I'll add a favicon to ScratchBux.
> https://github.com/MCloverz/sandbox/

edit _config.yml and add the following lines.
```yaml
plugins:
    - jekyll-seo-tag
```
Also create a copy of the _includes/head.html  in the repository as head.html (without the _includes/).

**Comment by MCloverz** [comment]
> ```yaml
> plugins:
>     - jekyll-seo-tag
> ```

Will do, I'll work on ScratchBux first.

**Comment by smileycreations15** [comment]
@MCloverz When you will edit the homepage?

**Comment by MCloverz** [comment]
> @MCloverz When you will edit the homepage?

Just did, I am currently multi-tasking between Scratch and GitHub.

**Comment by smileycreations15** [comment]
> > @MCloverz When you will edit the homepage?
> 
> Just did, I am currently multi-tasking between Scratch and GitHub.

I am multitasking between github, trello and scratch

**Comment by MCloverz** [comment]
> > > @MCloverz When you will edit the homepage?
> > 
> > 
> > Just did, I am currently multi-tasking between Scratch and GitHub.
> 
> I am multitasking between github, trello and scratch

It still doesn't seem to be working. Can you fork the sandbox repo and fix it?

**Comment by MCloverz** [comment]
Also, I'm re-uploading the favicon for ScratchBux. I've made the coin bigger.

**Comment by smileycreations15** [comment]
> > > > @MCloverz When you will edit the homepage?
> > > 
> > > 
> > > Just did, I am currently multi-tasking between Scratch and GitHub.
> > 
> > 
> > I am multitasking between github, trello and scratch
> 
> It still doesn't seem to be working. Can you fork the sandbox repo and fix it?

Yes!

**Comment by MCloverz** [comment]
> > > > > @MCloverz When you will edit the homepage?
> > > > 
> > > > 
> > > > Just did, I am currently multi-tasking between Scratch and GitHub.
> > > 
> > > 
> > > I am multitasking between github, trello and scratch
> > 
> > 
> > It still doesn't seem to be working. Can you fork the sandbox repo and fix it?
> 
> Yes!

Thanks!

**Comment by smileycreations15** [comment]
@MCloverz I created a pull request on your sandbox.

**Comment by MCloverz** [comment]
> @MCloverz I created a pull request on your sandbox.

I see.

**Comment by MCloverz** [comment]
> > @MCloverz I created a pull request on your sandbox.
> 
> I see.

It currently only shows your default favicon. How do you add the current favicon.png? It's the SSB logo.

**Comment by smileycreations15** [comment]
> > > @MCloverz I created a pull request on your sandbox.
> > 
> > 
> > I see.
> 
> It currently only shows your default favicon. How do you add the current favicon.png? It's the SSB logo.

Try clearing your cache.

**Comment by MCloverz** [comment]
> > > > @MCloverz I created a pull request on your sandbox.
> > > 
> > > 
> > > I see.
> > 
> > 
> > It currently only shows your default favicon. How do you add the current favicon.png? It's the SSB logo.
> 
> Try clearing your cache.

NVM, it changed! I'll try to learn from 'inspecting' your code. Thanks!

**Comment by smileycreations15** [comment]
@MCloverz It is ready to merge. Now go ahead and merge the PR (pull request).

**Comment by MCloverz** [comment]
> @MCloverz It is ready to merge. Now go ahead and merge the PR (pull request).

I'm gonna try something first.

**Comment by smileycreations15** [comment]
> > @MCloverz It is ready to merge. Now go ahead and merge the PR (pull request).
> 
> I'm gonna try something first.

Do you need write (push) access?

**Comment by MCloverz** [comment]
> > > @MCloverz It is ready to merge. Now go ahead and merge the PR (pull request).
> > 
> > 
> > I'm gonna try something first.
> 
> Do you need write (push) access?

No thanks, there is no need for a merge! Thanks! I copied the default.html and it worked! Thanks so much! You may delete your fork if you wish.

**Comment by smileycreations15** [comment]
> No thanks, there is no need for a merge! Thanks! I copied the default.html and it worked! Thanks so much! You may delete your fork if you wish.

You need to also copy the style.css

**Comment by MCloverz** [comment]
> > No thanks, there is no need for a merge! Thanks! I copied the default.html and it worked! Thanks so much! You may delete your fork if you wish.
> 
> You need to also copy the style.css

Oof, what does that do?

**Comment by MCloverz** [comment]
> > > No thanks, there is no need for a merge! Thanks! I copied the default.html and it worked! Thanks so much! You may delete your fork if you wish.
> > 
> > 
> > You need to also copy the style.css
> 
> Oof, what does that do?

I know what CSS is, just curious why it's necessary.

**Comment by smileycreations15** [comment]
> > > No thanks, there is no need for a merge! Thanks! I copied the default.html and it worked! Thanks so much! You may delete your fork if you wish.
> > 
> > 
> > You need to also copy the style.css
> 
> Oof, what does that do?

It is the style that makes the website more beautiful. If you don't remove the slate theme, it is all ok.

**Comment by MCloverz** [comment]
> > > > No thanks, there is no need for a merge! Thanks! I copied the default.html and it worked! Thanks so much! You may delete your fork if you wish.
> > > 
> > > 
> > > You need to also copy the style.css
> > 
> > 
> > Oof, what does that do?
> 
> It is the style that makes the website more beautiful. If you don't remove the slate theme, it is all ok.

Okay then.

**Comment by MCloverz** [comment]
I'm going to sleep, it's currently 11 pm for me and I am **so** tired...

**Comment by smileycreations15** [comment]
> I'm going to sleep, it's currently 11 pm for me and I am **so** tired...

ok
